# Generated by Django 4.1.7 on 2025-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0011_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='empenho',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='n_nfe',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nfe',
        ),
        migrations.AddField(
            model_name='cliente',
            name='comprovante_entrega',
            field=models.FileField(blank=True, default='0', max_length=500, upload_to='comprovantes/'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
