# Generated by Django 4.1.7 on 2025-01-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0012_remove_cliente_categoria_remove_cliente_empenho_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
